# Generated by Django 3.2.9 on 2022-03-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_contractor_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='rating',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
