# Generated by Django 3.2.9 on 2022-03-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_contractor_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
