# Generated by Django 3.2.9 on 2022-03-26 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_contractor_photo'),
        ('api', '0002_project_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='contractors',
        ),
        migrations.AddField(
            model_name='project',
            name='contractors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.contractor'),
        ),
        migrations.CreateModel(
            name='WorkerAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_time', models.TimeField()),
                ('exit_time', models.TimeField()),
                ('total_time', models.IntegerField()),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.worker')),
            ],
        ),
        migrations.CreateModel(
            name='ContractorAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enter_time', models.TimeField()),
                ('exit_time', models.TimeField()),
                ('total_time', models.IntegerField()),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.contractor')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.project')),
            ],
        ),
    ]
