# Generated by Django 3.2.9 on 2022-03-26 16:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220326_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorattendance',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='workerattendance',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
