# Generated by Django 3.2.9 on 2022-03-26 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_task_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorattendance',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
