# Generated by Django 3.2.9 on 2022-03-27 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_workerattendance_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerattendance',
            name='enter_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workerattendance',
            name='exit_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
