# Generated by Django 3.2.9 on 2022-03-27 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20220327_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='workerattendance',
            name='status',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='workerattendance',
            name='total_time',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
