# Generated by Django 3.2.9 on 2022-03-27 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_contractor_description'),
        ('api', '0012_auto_20220327_0715'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('helmet', models.CharField(default='Helmet Violation', max_length=30)),
                ('mask', models.CharField(default='Mask Violation', max_length=30)),
                ('photo', models.ImageField(upload_to='')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.contractor')),
            ],
        ),
        migrations.CreateModel(
            name='ContractorViolation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('helmet', models.CharField(default='Helmet Violation', max_length=30)),
                ('mask', models.CharField(default='Mask Violation', max_length=30)),
                ('photo', models.ImageField(upload_to='')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.contractor')),
            ],
        ),
    ]
