# Generated by Django 3.2.9 on 2022-03-27 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_contractorviolation_workerviolation'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorviolation',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='workerviolation',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
